//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parafait_FnB_Kiosk.UserServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://semnox.com/", ConfigurationName="UserServices.UserServicesSoap")]
    public interface UserServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/ValidateLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Parafait_FnB_Kiosk.UserServices.KeyValueStruct[] ValidateLogin(string loginId, string passwordPassed, string loginCardNumber, string macAddressPassed, bool isGameMachine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/ValidateLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.KeyValueStruct[]> ValidateLoginAsync(string loginId, string passwordPassed, string loginCardNumber, string macAddressPassed, bool isGameMachine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/PerformLogout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PerformLogout(string loginId, string macAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/PerformLogout", ReplyAction="*")]
        System.Threading.Tasks.Task PerformLogoutAsync(string loginId, string macAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/PerformAlohaClockIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PerformAlohaClockIn(string loginId, string posIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/PerformAlohaClockIn", ReplyAction="*")]
        System.Threading.Tasks.Task PerformAlohaClockInAsync(string loginId, string posIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/PerformAlohaClockOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PerformAlohaClockOut(string loginId, string posIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/PerformAlohaClockOut", ReplyAction="*")]
        System.Threading.Tasks.Task PerformAlohaClockOutAsync(string loginId, string posIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/HandleOpenShift", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Parafait_FnB_Kiosk.UserServices.KeyValueStruct[] HandleOpenShift(string loginId, string macAddressPassed, string actionPassed, string shiftAmount, string shiftCardCount, string shiftGameCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/HandleOpenShift", ReplyAction="*")]
        System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.KeyValueStruct[]> HandleOpenShiftAsync(string loginId, string macAddressPassed, string actionPassed, string shiftAmount, string shiftCardCount, string shiftGameCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/GetShiftStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Parafait_FnB_Kiosk.UserServices.KeyValueStruct[] GetShiftStatus(string loginId, string macAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/GetShiftStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.KeyValueStruct[]> GetShiftStatusAsync(string loginId, string macAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/GetUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Parafait_FnB_Kiosk.UserServices.UsersDTO[] GetUsers(string lastSyncTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.UsersDTO[]> GetUsersAsync(string lastSyncTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/GetShiftDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Parafait_FnB_Kiosk.UserServices.KeyValueStruct[] GetShiftDetails(string loginId, string macAddressPassed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/GetShiftDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.KeyValueStruct[]> GetShiftDetailsAsync(string loginId, string macAddressPassed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/ValidateLoginUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Parafait_FnB_Kiosk.UserServices.CoreKeyValueStruct[] ValidateLoginUser(Parafait_FnB_Kiosk.UserServices.UserAuthParams userAuthParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/ValidateLoginUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.CoreKeyValueStruct[]> ValidateLoginUserAsync(Parafait_FnB_Kiosk.UserServices.UserAuthParams userAuthParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Parafait_FnB_Kiosk.UserServices.ChangePasswordResponse ChangePassword(Parafait_FnB_Kiosk.UserServices.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.ChangePasswordResponse> ChangePasswordAsync(Parafait_FnB_Kiosk.UserServices.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/ResetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Parafait_FnB_Kiosk.UserServices.ResetPasswordResponse ResetPassword(Parafait_FnB_Kiosk.UserServices.ResetPasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/ResetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.ResetPasswordResponse> ResetPasswordAsync(Parafait_FnB_Kiosk.UserServices.ResetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/GetManagementFormAccess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Parafait_FnB_Kiosk.UserServices.ManagementFormAccessDTO[] GetManagementFormAccess(int userId, string functionGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/GetManagementFormAccess", ReplyAction="*")]
        System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.ManagementFormAccessDTO[]> GetManagementFormAccessAsync(int userId, string functionGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/GetManagementForms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Parafait_FnB_Kiosk.UserServices.ManagementFormDTO[] GetManagementForms(string functionGroup, int siteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://semnox.com/GetManagementForms", ReplyAction="*")]
        System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.ManagementFormDTO[]> GetManagementFormsAsync(string functionGroup, int siteId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://semnox.com/")]
    public partial class KeyValueStruct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://semnox.com/")]
    public partial class ManagementFormDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int managementFormIdField;
        
        private string functionGroupField;
        
        private string groupNameField;
        
        private string formNameField;
        
        private string formLookupTableField;
        
        private string fontImageIconField;
        
        private string formTargetPathField;
        
        private System.Nullable<int> displayOrderField;
        
        private System.Nullable<bool> enableAccessField;
        
        private System.Guid guidField;
        
        private System.Nullable<int> siteIdField;
        
        private System.Nullable<bool> synchStatusField;
        
        private System.Nullable<int> masterEntityIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ManagementFormId {
            get {
                return this.managementFormIdField;
            }
            set {
                this.managementFormIdField = value;
                this.RaisePropertyChanged("ManagementFormId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FunctionGroup {
            get {
                return this.functionGroupField;
            }
            set {
                this.functionGroupField = value;
                this.RaisePropertyChanged("FunctionGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("GroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FormName {
            get {
                return this.formNameField;
            }
            set {
                this.formNameField = value;
                this.RaisePropertyChanged("FormName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FormLookupTable {
            get {
                return this.formLookupTableField;
            }
            set {
                this.formLookupTableField = value;
                this.RaisePropertyChanged("FormLookupTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FontImageIcon {
            get {
                return this.fontImageIconField;
            }
            set {
                this.fontImageIconField = value;
                this.RaisePropertyChanged("FontImageIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FormTargetPath {
            get {
                return this.formTargetPathField;
            }
            set {
                this.formTargetPathField = value;
                this.RaisePropertyChanged("FormTargetPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> DisplayOrder {
            get {
                return this.displayOrderField;
            }
            set {
                this.displayOrderField = value;
                this.RaisePropertyChanged("DisplayOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> EnableAccess {
            get {
                return this.enableAccessField;
            }
            set {
                this.enableAccessField = value;
                this.RaisePropertyChanged("EnableAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> SiteId {
            get {
                return this.siteIdField;
            }
            set {
                this.siteIdField = value;
                this.RaisePropertyChanged("SiteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<bool> SynchStatus {
            get {
                return this.synchStatusField;
            }
            set {
                this.synchStatusField = value;
                this.RaisePropertyChanged("SynchStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> MasterEntityId {
            get {
                return this.masterEntityIdField;
            }
            set {
                this.masterEntityIdField = value;
                this.RaisePropertyChanged("MasterEntityId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://semnox.com/")]
    public partial class ManagementFormAccessDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int managementFormAccessIdField;
        
        private int roleIdField;
        
        private string mainMenuField;
        
        private string formNameField;
        
        private string accessAllowedField;
        
        private System.Nullable<int> functionIdField;
        
        private string functionGroupField;
        
        private System.Guid guidField;
        
        private System.Nullable<int> siteIdField;
        
        private System.Nullable<bool> synchStatusField;
        
        private System.Nullable<int> masterEntityIdField;
        
        private System.Nullable<System.Guid> functionGUIDField;
        
        private string fontImageIconField;
        
        private string formTargetPathField;
        
        private ManagementFormAccessDTO[] childFormsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ManagementFormAccessId {
            get {
                return this.managementFormAccessIdField;
            }
            set {
                this.managementFormAccessIdField = value;
                this.RaisePropertyChanged("ManagementFormAccessId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MainMenu {
            get {
                return this.mainMenuField;
            }
            set {
                this.mainMenuField = value;
                this.RaisePropertyChanged("MainMenu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FormName {
            get {
                return this.formNameField;
            }
            set {
                this.formNameField = value;
                this.RaisePropertyChanged("FormName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AccessAllowed {
            get {
                return this.accessAllowedField;
            }
            set {
                this.accessAllowedField = value;
                this.RaisePropertyChanged("AccessAllowed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> FunctionId {
            get {
                return this.functionIdField;
            }
            set {
                this.functionIdField = value;
                this.RaisePropertyChanged("FunctionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FunctionGroup {
            get {
                return this.functionGroupField;
            }
            set {
                this.functionGroupField = value;
                this.RaisePropertyChanged("FunctionGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> SiteId {
            get {
                return this.siteIdField;
            }
            set {
                this.siteIdField = value;
                this.RaisePropertyChanged("SiteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> SynchStatus {
            get {
                return this.synchStatusField;
            }
            set {
                this.synchStatusField = value;
                this.RaisePropertyChanged("SynchStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> MasterEntityId {
            get {
                return this.masterEntityIdField;
            }
            set {
                this.masterEntityIdField = value;
                this.RaisePropertyChanged("MasterEntityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.Guid> FunctionGUID {
            get {
                return this.functionGUIDField;
            }
            set {
                this.functionGUIDField = value;
                this.RaisePropertyChanged("FunctionGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FontImageIcon {
            get {
                return this.fontImageIconField;
            }
            set {
                this.fontImageIconField = value;
                this.RaisePropertyChanged("FontImageIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FormTargetPath {
            get {
                return this.formTargetPathField;
            }
            set {
                this.formTargetPathField = value;
                this.RaisePropertyChanged("FormTargetPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public ManagementFormAccessDTO[] ChildForms {
            get {
                return this.childFormsField;
            }
            set {
                this.childFormsField = value;
                this.RaisePropertyChanged("ChildForms");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://semnox.com/")]
    public partial class CoreKeyValueStruct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://semnox.com/")]
    public partial class UserAuthParams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginIdField;
        
        private string emailField;
        
        private string passwordPassedField;
        
        private string newPasswordField;
        
        private string macAddressPassedField;
        
        private bool isGameMachineField;
        
        public UserAuthParams() {
            this.isGameMachineField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LoginId {
            get {
                return this.loginIdField;
            }
            set {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PasswordPassed {
            get {
                return this.passwordPassedField;
            }
            set {
                this.passwordPassedField = value;
                this.RaisePropertyChanged("PasswordPassed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("NewPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MacAddressPassed {
            get {
                return this.macAddressPassedField;
            }
            set {
                this.macAddressPassedField = value;
                this.RaisePropertyChanged("MacAddressPassed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IsGameMachine {
            get {
                return this.isGameMachineField;
            }
            set {
                this.isGameMachineField = value;
                this.RaisePropertyChanged("IsGameMachine");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://semnox.com/")]
    public partial class UsersDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userIdField;
        
        private string userNameField;
        
        private string loginIdField;
        
        private int roleIdField;
        
        private string cardNumberField;
        
        private System.DateTime lastLoginTimeField;
        
        private System.DateTime logoutTimeField;
        
        private string overrideFingerPrintField;
        
        private byte[] passwordHashField;
        
        private string passwordSaltField;
        
        private string passwordField;
        
        private int masterEntityIdField;
        
        private int posTypeIdField;
        
        private int departmentIdField;
        
        private string departmentNameField;
        
        private System.DateTime empStartDateField;
        
        private System.DateTime empEndDateField;
        
        private string empEndReasonField;
        
        private int managerIdField;
        
        private string empLastNameField;
        
        private string empNumberField;
        
        private string companyAdministratorField;
        
        private int fingerNumberField;
        
        private string userStatusField;
        
        private System.DateTime passwordChangeDateField;
        
        private int invalidAccessAttemptsField;
        
        private System.DateTime lockedOutTimeField;
        
        private bool passwordChangeOnNextLoginField;
        
        private string emailField;
        
        private bool isActiveField;
        
        private string createdByField;
        
        private System.DateTime creationDateField;
        
        private string lastUpdatedByField;
        
        private System.DateTime lastUpdatedDateField;
        
        private string guidField;
        
        private int siteIdField;
        
        private bool synchStatusField;
        
        private bool isChangedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LoginId {
            get {
                return this.loginIdField;
            }
            set {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
                this.RaisePropertyChanged("CardNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime LastLoginTime {
            get {
                return this.lastLoginTimeField;
            }
            set {
                this.lastLoginTimeField = value;
                this.RaisePropertyChanged("LastLoginTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime LogoutTime {
            get {
                return this.logoutTimeField;
            }
            set {
                this.logoutTimeField = value;
                this.RaisePropertyChanged("LogoutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OverrideFingerPrint {
            get {
                return this.overrideFingerPrintField;
            }
            set {
                this.overrideFingerPrintField = value;
                this.RaisePropertyChanged("OverrideFingerPrint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=8)]
        public byte[] PasswordHash {
            get {
                return this.passwordHashField;
            }
            set {
                this.passwordHashField = value;
                this.RaisePropertyChanged("PasswordHash");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PasswordSalt {
            get {
                return this.passwordSaltField;
            }
            set {
                this.passwordSaltField = value;
                this.RaisePropertyChanged("PasswordSalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int MasterEntityId {
            get {
                return this.masterEntityIdField;
            }
            set {
                this.masterEntityIdField = value;
                this.RaisePropertyChanged("MasterEntityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int PosTypeId {
            get {
                return this.posTypeIdField;
            }
            set {
                this.posTypeIdField = value;
                this.RaisePropertyChanged("PosTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int DepartmentId {
            get {
                return this.departmentIdField;
            }
            set {
                this.departmentIdField = value;
                this.RaisePropertyChanged("DepartmentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
                this.RaisePropertyChanged("DepartmentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime EmpStartDate {
            get {
                return this.empStartDateField;
            }
            set {
                this.empStartDateField = value;
                this.RaisePropertyChanged("EmpStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime EmpEndDate {
            get {
                return this.empEndDateField;
            }
            set {
                this.empEndDateField = value;
                this.RaisePropertyChanged("EmpEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string EmpEndReason {
            get {
                return this.empEndReasonField;
            }
            set {
                this.empEndReasonField = value;
                this.RaisePropertyChanged("EmpEndReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int ManagerId {
            get {
                return this.managerIdField;
            }
            set {
                this.managerIdField = value;
                this.RaisePropertyChanged("ManagerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string EmpLastName {
            get {
                return this.empLastNameField;
            }
            set {
                this.empLastNameField = value;
                this.RaisePropertyChanged("EmpLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string EmpNumber {
            get {
                return this.empNumberField;
            }
            set {
                this.empNumberField = value;
                this.RaisePropertyChanged("EmpNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CompanyAdministrator {
            get {
                return this.companyAdministratorField;
            }
            set {
                this.companyAdministratorField = value;
                this.RaisePropertyChanged("CompanyAdministrator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int FingerNumber {
            get {
                return this.fingerNumberField;
            }
            set {
                this.fingerNumberField = value;
                this.RaisePropertyChanged("FingerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string UserStatus {
            get {
                return this.userStatusField;
            }
            set {
                this.userStatusField = value;
                this.RaisePropertyChanged("UserStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public System.DateTime PasswordChangeDate {
            get {
                return this.passwordChangeDateField;
            }
            set {
                this.passwordChangeDateField = value;
                this.RaisePropertyChanged("PasswordChangeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int InvalidAccessAttempts {
            get {
                return this.invalidAccessAttemptsField;
            }
            set {
                this.invalidAccessAttemptsField = value;
                this.RaisePropertyChanged("InvalidAccessAttempts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public System.DateTime LockedOutTime {
            get {
                return this.lockedOutTimeField;
            }
            set {
                this.lockedOutTimeField = value;
                this.RaisePropertyChanged("LockedOutTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public bool PasswordChangeOnNextLogin {
            get {
                return this.passwordChangeOnNextLoginField;
            }
            set {
                this.passwordChangeOnNextLoginField = value;
                this.RaisePropertyChanged("PasswordChangeOnNextLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public System.DateTime CreationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
                this.RaisePropertyChanged("CreationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string LastUpdatedBy {
            get {
                return this.lastUpdatedByField;
            }
            set {
                this.lastUpdatedByField = value;
                this.RaisePropertyChanged("LastUpdatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public System.DateTime LastUpdatedDate {
            get {
                return this.lastUpdatedDateField;
            }
            set {
                this.lastUpdatedDateField = value;
                this.RaisePropertyChanged("LastUpdatedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public int SiteId {
            get {
                return this.siteIdField;
            }
            set {
                this.siteIdField = value;
                this.RaisePropertyChanged("SiteId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public bool SynchStatus {
            get {
                return this.synchStatusField;
            }
            set {
                this.synchStatusField = value;
                this.RaisePropertyChanged("SynchStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public bool IsChanged {
            get {
                return this.isChangedField;
            }
            set {
                this.isChangedField = value;
                this.RaisePropertyChanged("IsChanged");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="http://semnox.com/", IsWrapped=true)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://semnox.com/", Order=0)]
        public Parafait_FnB_Kiosk.UserServices.UserAuthParams userAuthParams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://semnox.com/", Order=1)]
        public string message;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(Parafait_FnB_Kiosk.UserServices.UserAuthParams userAuthParams, string message) {
            this.userAuthParams = userAuthParams;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://semnox.com/", IsWrapped=true)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://semnox.com/", Order=0)]
        public bool ChangePasswordResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://semnox.com/", Order=1)]
        public string message;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(bool ChangePasswordResult, string message) {
            this.ChangePasswordResult = ChangePasswordResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetPassword", WrapperNamespace="http://semnox.com/", IsWrapped=true)]
    public partial class ResetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://semnox.com/", Order=0)]
        public Parafait_FnB_Kiosk.UserServices.UserAuthParams userAuthParams;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://semnox.com/", Order=1)]
        public string message;
        
        public ResetPasswordRequest() {
        }
        
        public ResetPasswordRequest(Parafait_FnB_Kiosk.UserServices.UserAuthParams userAuthParams, string message) {
            this.userAuthParams = userAuthParams;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetPasswordResponse", WrapperNamespace="http://semnox.com/", IsWrapped=true)]
    public partial class ResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://semnox.com/", Order=0)]
        public bool ResetPasswordResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://semnox.com/", Order=1)]
        public string message;
        
        public ResetPasswordResponse() {
        }
        
        public ResetPasswordResponse(bool ResetPasswordResult, string message) {
            this.ResetPasswordResult = ResetPasswordResult;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServicesSoapChannel : Parafait_FnB_Kiosk.UserServices.UserServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServicesSoapClient : System.ServiceModel.ClientBase<Parafait_FnB_Kiosk.UserServices.UserServicesSoap>, Parafait_FnB_Kiosk.UserServices.UserServicesSoap {
        
        public UserServicesSoapClient() {
        }
        
        public UserServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public Parafait_FnB_Kiosk.UserServices.KeyValueStruct[] ValidateLogin(string loginId, string passwordPassed, string loginCardNumber, string macAddressPassed, bool isGameMachine) {
            return base.Channel.ValidateLogin(loginId, passwordPassed, loginCardNumber, macAddressPassed, isGameMachine);
        }
        
        public System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.KeyValueStruct[]> ValidateLoginAsync(string loginId, string passwordPassed, string loginCardNumber, string macAddressPassed, bool isGameMachine) {
            return base.Channel.ValidateLoginAsync(loginId, passwordPassed, loginCardNumber, macAddressPassed, isGameMachine);
        }
        
        public void PerformLogout(string loginId, string macAddress) {
            base.Channel.PerformLogout(loginId, macAddress);
        }
        
        public System.Threading.Tasks.Task PerformLogoutAsync(string loginId, string macAddress) {
            return base.Channel.PerformLogoutAsync(loginId, macAddress);
        }
        
        public void PerformAlohaClockIn(string loginId, string posIdentifier) {
            base.Channel.PerformAlohaClockIn(loginId, posIdentifier);
        }
        
        public System.Threading.Tasks.Task PerformAlohaClockInAsync(string loginId, string posIdentifier) {
            return base.Channel.PerformAlohaClockInAsync(loginId, posIdentifier);
        }
        
        public void PerformAlohaClockOut(string loginId, string posIdentifier) {
            base.Channel.PerformAlohaClockOut(loginId, posIdentifier);
        }
        
        public System.Threading.Tasks.Task PerformAlohaClockOutAsync(string loginId, string posIdentifier) {
            return base.Channel.PerformAlohaClockOutAsync(loginId, posIdentifier);
        }
        
        public Parafait_FnB_Kiosk.UserServices.KeyValueStruct[] HandleOpenShift(string loginId, string macAddressPassed, string actionPassed, string shiftAmount, string shiftCardCount, string shiftGameCard) {
            return base.Channel.HandleOpenShift(loginId, macAddressPassed, actionPassed, shiftAmount, shiftCardCount, shiftGameCard);
        }
        
        public System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.KeyValueStruct[]> HandleOpenShiftAsync(string loginId, string macAddressPassed, string actionPassed, string shiftAmount, string shiftCardCount, string shiftGameCard) {
            return base.Channel.HandleOpenShiftAsync(loginId, macAddressPassed, actionPassed, shiftAmount, shiftCardCount, shiftGameCard);
        }
        
        public Parafait_FnB_Kiosk.UserServices.KeyValueStruct[] GetShiftStatus(string loginId, string macAddress) {
            return base.Channel.GetShiftStatus(loginId, macAddress);
        }
        
        public System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.KeyValueStruct[]> GetShiftStatusAsync(string loginId, string macAddress) {
            return base.Channel.GetShiftStatusAsync(loginId, macAddress);
        }
        
        public Parafait_FnB_Kiosk.UserServices.UsersDTO[] GetUsers(string lastSyncTime) {
            return base.Channel.GetUsers(lastSyncTime);
        }
        
        public System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.UsersDTO[]> GetUsersAsync(string lastSyncTime) {
            return base.Channel.GetUsersAsync(lastSyncTime);
        }
        
        public Parafait_FnB_Kiosk.UserServices.KeyValueStruct[] GetShiftDetails(string loginId, string macAddressPassed) {
            return base.Channel.GetShiftDetails(loginId, macAddressPassed);
        }
        
        public System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.KeyValueStruct[]> GetShiftDetailsAsync(string loginId, string macAddressPassed) {
            return base.Channel.GetShiftDetailsAsync(loginId, macAddressPassed);
        }
        
        public Parafait_FnB_Kiosk.UserServices.CoreKeyValueStruct[] ValidateLoginUser(Parafait_FnB_Kiosk.UserServices.UserAuthParams userAuthParams) {
            return base.Channel.ValidateLoginUser(userAuthParams);
        }
        
        public System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.CoreKeyValueStruct[]> ValidateLoginUserAsync(Parafait_FnB_Kiosk.UserServices.UserAuthParams userAuthParams) {
            return base.Channel.ValidateLoginUserAsync(userAuthParams);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parafait_FnB_Kiosk.UserServices.ChangePasswordResponse Parafait_FnB_Kiosk.UserServices.UserServicesSoap.ChangePassword(Parafait_FnB_Kiosk.UserServices.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public bool ChangePassword(Parafait_FnB_Kiosk.UserServices.UserAuthParams userAuthParams, ref string message) {
            Parafait_FnB_Kiosk.UserServices.ChangePasswordRequest inValue = new Parafait_FnB_Kiosk.UserServices.ChangePasswordRequest();
            inValue.userAuthParams = userAuthParams;
            inValue.message = message;
            Parafait_FnB_Kiosk.UserServices.ChangePasswordResponse retVal = ((Parafait_FnB_Kiosk.UserServices.UserServicesSoap)(this)).ChangePassword(inValue);
            message = retVal.message;
            return retVal.ChangePasswordResult;
        }
        
        public System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.ChangePasswordResponse> ChangePasswordAsync(Parafait_FnB_Kiosk.UserServices.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Parafait_FnB_Kiosk.UserServices.ResetPasswordResponse Parafait_FnB_Kiosk.UserServices.UserServicesSoap.ResetPassword(Parafait_FnB_Kiosk.UserServices.ResetPasswordRequest request) {
            return base.Channel.ResetPassword(request);
        }
        
        public bool ResetPassword(Parafait_FnB_Kiosk.UserServices.UserAuthParams userAuthParams, ref string message) {
            Parafait_FnB_Kiosk.UserServices.ResetPasswordRequest inValue = new Parafait_FnB_Kiosk.UserServices.ResetPasswordRequest();
            inValue.userAuthParams = userAuthParams;
            inValue.message = message;
            Parafait_FnB_Kiosk.UserServices.ResetPasswordResponse retVal = ((Parafait_FnB_Kiosk.UserServices.UserServicesSoap)(this)).ResetPassword(inValue);
            message = retVal.message;
            return retVal.ResetPasswordResult;
        }
        
        public System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.ResetPasswordResponse> ResetPasswordAsync(Parafait_FnB_Kiosk.UserServices.ResetPasswordRequest request) {
            return base.Channel.ResetPasswordAsync(request);
        }
        
        public Parafait_FnB_Kiosk.UserServices.ManagementFormAccessDTO[] GetManagementFormAccess(int userId, string functionGroup) {
            return base.Channel.GetManagementFormAccess(userId, functionGroup);
        }
        
        public System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.ManagementFormAccessDTO[]> GetManagementFormAccessAsync(int userId, string functionGroup) {
            return base.Channel.GetManagementFormAccessAsync(userId, functionGroup);
        }
        
        public Parafait_FnB_Kiosk.UserServices.ManagementFormDTO[] GetManagementForms(string functionGroup, int siteId) {
            return base.Channel.GetManagementForms(functionGroup, siteId);
        }
        
        public System.Threading.Tasks.Task<Parafait_FnB_Kiosk.UserServices.ManagementFormDTO[]> GetManagementFormsAsync(string functionGroup, int siteId) {
            return base.Channel.GetManagementFormsAsync(functionGroup, siteId);
        }
    }
}
